language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
    - lambda/node_modules
script:
    - pip install awscli --upgrade --user
    - npm install -g serverless
    - bash ./deploy_client.sh
    - bash ./deploy_lambda.sh
